server:
  port: 9006

spring:
  application:
    name: CONFIG-SERVER
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/CrazySkunk/config-server
#          clone-on-start: true