server:
  port: 9002

spring:
  application:
    name: DEPARTMENT-SERVICE
  cloud:
    config:
      enabled: true
      uri: http://localhost:9005


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost